/* World-map configuration — COMPANION CAMPAIGNS.

   Progression belongs to the active companion's CAMPAIGN, not the hero's
   lifetime totals. Every campaign walks the same three SHARED WORLDS
   (Shadow Ninja Village → Legend of the Samurai → Speed Realm) and ends in
   that companion's exclusive FINALE WORLD — 4 worlds × 36 quests = 144 steps.
   Campaign progress = the bond's quests_done (starts at 0 for every new
   partner); completing the finale makes the companion LEGENDARY.

   Each world spans 36 quests and paints 36 nodes onto its map: every
   approved quest moves the hero one step along the path. Node positions are
   generated by interpolating along hand-placed percentage ANCHORS that trace
   the painted path (x = % from left, y = % from top) — tweak the anchors to
   re-shape a world's route, no other changes needed.

   Along the way, seven named LANDMARKS mark memorable places, and node 36 is
   the world's boss-style trial. */

import { ThemeId, CompanionBond } from "./game";
import { worldMapArt } from "./assets";

export type NodeKind = "quest" | "landmark" | "final";

export interface MapNode {
  id: string;
  name: string;
  x: number; // % from left of the map image
  y: number; // % from top of the map image
  requires: number; // total quests completed needed to clear this node
  kind: NodeKind;
}

export interface WorldMapDef {
  id: string; // matches the public/worlds/<id>/ folder
  name: string;
  /** Set for the three shared worlds; finale worlds have no theme/palette. */
  theme?: ThemeId;
  map: string; // path under /public
  accent: string; // themed glow colour for the path + nodes
  /** Hand-placed waypoints tracing the painted path — adjust these freely. */
  anchors: { x: number; y: number }[];
  /** The boss-style milestone that closes the world (node 36). */
  finale: { name: string; icon: string; blurb: string };
  /** What completing the world unlocks. */
  reward: { companion: string; blurb: string };
  levels: MapNode[];
}

/* Every world is 36 quests; landmarks sit at these steps within it. */
export const CHAPTER_SPAN = 36;
const LANDMARK_STEPS = [1, 4, 8, 13, 18, 24, 30];

/* Campaign shape: 3 shared worlds + 1 companion-exclusive finale world. */
export const SHARED_WORLDS: ThemeId[] = ["ninja", "samurai", "speed"];
export const WORLDS_PER_CAMPAIGN = 4;
export const CAMPAIGN_TOTAL = CHAPTER_SPAN * WORLDS_PER_CAMPAIGN; // 144 — mirrors campaign_total() in SQL

/** @deprecated legacy alias — the shared-world order within a campaign. */
export const WORLD_ORDER = SHARED_WORLDS;

/* ---------- Finale worlds ----------
   Every companion's campaign ends in its own painted world. Anchors trace
   each map's road from its starting plaza to the Legend Ceremony gate. */

export interface FinaleWorldDef {
  id: string;
  name: string;
  accent: string;
  finale: { name: string; icon: string; blurb: string };
  /** Painted map + path data — present once the world's art is delivered.
      With all three set, the finale renders exactly like a shared world. */
  map?: string;
  anchors?: { x: number; y: number }[];
  stops?: string[];
}

export const FINALE_WORLDS: Record<string, FinaleWorldDef> = {
  dragon: {
    id: "dragon-volcano",
    name: "Dragon Volcano",
    accent: "#ff7a3d",
    finale: { name: "Trial of Flames", icon: "flame", blurb: "Climb the caldera and light the eternal fire with Ember." },
    map: worldMapArt("dragon-volcano"),
    // golden road: ashen shore at the bottom → winding up past the crystal
    // cave and dragon gates → the grand ceremony gate under the light beam
    anchors: [
      { x: 47, y: 93 },
      { x: 50, y: 86 },
      { x: 46, y: 80 },
      { x: 50, y: 74 },
      { x: 46, y: 68 },
      { x: 53, y: 60 },
      { x: 50, y: 56 },
      { x: 58, y: 51 },
      { x: 56, y: 46 },
      { x: 60, y: 42 },
      { x: 56, y: 37 },
      { x: 60, y: 33 },
      { x: 56, y: 29 },
      { x: 57, y: 25 },
      { x: 61, y: 18 },
    ],
    stops: [
      "Ashen Shore",
      "Ember Gate",
      "Crystal Hollow",
      "Lavafall Crossing",
      "Spark Shrine",
      "Dragon Steps",
      "Molten Terrace",
    ],
  },
  ninja: {
    id: "shadow-temple",
    name: "Shadow Temple",
    accent: "#9a86e0",
    finale: { name: "Trial of Shadows", icon: "sword", blurb: "Pass the silent halls where only true ninja may walk." },
    map: worldMapArt("shadow-temple"),
    anchors: [
      { x: 50, y: 90 },
      { x: 52, y: 82 },
      { x: 55, y: 75 },
      { x: 53, y: 70 },
      { x: 55, y: 63 },
      { x: 57, y: 57 },
      { x: 62, y: 52 },
      { x: 67, y: 45 },
      { x: 60, y: 40 },
      { x: 67, y: 34 },
      { x: 62, y: 28 },
      { x: 64, y: 24 },
      { x: 63, y: 16 },
    ],
    stops: [
      "Moon Gate",
      "Bamboo Hollow",
      "Crystal Grotto",
      "Spirit Bridge",
      "Lantern Steps",
      "Blossom Shrine",
      "Silent Pagoda",
    ],
  },
  robot: {
    id: "robot-laboratory",
    name: "Robot Laboratory",
    accent: "#4fb8ff",
    finale: { name: "Invention Trial", icon: "lightning", blurb: "Power up the great machine at the heart of the lab." },
    map: worldMapArt("robot-laboratory"),
    anchors: [
      { x: 38, y: 96 },
      { x: 42, y: 91 },
      { x: 46, y: 84 },
      { x: 46, y: 78 },
      { x: 47, y: 73 },
      { x: 52, y: 66 },
      { x: 55, y: 60 },
      { x: 60, y: 55 },
      { x: 61, y: 51 },
      { x: 57, y: 48 },
      { x: 62, y: 43 },
      { x: 58, y: 40 },
      { x: 57, y: 38 },
      { x: 60, y: 35 },
      { x: 59, y: 31 },
      { x: 60, y: 27 },
    ],
    stops: [
      "Assembly Bay",
      "Conveyor Run",
      "Hologram Hall",
      "Data Sphere",
      "Robo Depot",
      "Circuit Bridge",
      "Energy Vault",
    ],
  },
  fox: {
    id: "crystal-glacier",
    name: "Crystal Glacier",
    accent: "#5fd0ff",
    finale: { name: "Trial of Ice", icon: "sparkle", blurb: "Cross the frozen mirror sea to the aurora throne." },
    map: worldMapArt("crystal-glacier"),
    anchors: [
      { x: 45, y: 94 },
      { x: 44, y: 87 },
      { x: 46, y: 82 },
      { x: 43, y: 76 },
      { x: 47, y: 70 },
      { x: 43, y: 67 },
      { x: 54, y: 60 },
      { x: 50, y: 55 },
      { x: 46, y: 50 },
      { x: 43, y: 46 },
      { x: 40, y: 41 },
      { x: 46, y: 36 },
      { x: 52, y: 34 },
      { x: 57, y: 30 },
      { x: 56, y: 27 },
      { x: 64, y: 18 },
    ],
    stops: [
      "Frozen Shore",
      "Pine Hollow",
      "Ice Bridge",
      "Mirror Lake",
      "Aurora Falls",
      "Frost Gazebo",
      "Glacier Steps",
    ],
  },
  tiger: {
    id: "storm-mountain",
    name: "Storm Mountain",
    accent: "#ffe45e",
    finale: { name: "Thunder Trial", icon: "lightning", blurb: "Race the lightning to the peak where storms are born." },
    map: worldMapArt("storm-mountain"),
    anchors: [
      { x: 46, y: 94 },
      { x: 44, y: 87 },
      { x: 46, y: 81 },
      { x: 52, y: 75 },
      { x: 49, y: 70 },
      { x: 54, y: 65 },
      { x: 49, y: 60 },
      { x: 55, y: 55 },
      { x: 50, y: 50 },
      { x: 58, y: 44 },
      { x: 51, y: 37 },
      { x: 59, y: 30 },
      { x: 56, y: 26 },
      { x: 57, y: 19 },
    ],
    stops: [
      "Cloud Plaza",
      "Thunder Bridge",
      "Lightning Spire",
      "Storm Gazebo",
      "Skyfall Isles",
      "Tempest Walk",
      "Crystal Ring",
    ],
  },
  samurai: {
    id: "samurai-dojo",
    name: "Samurai Dojo",
    accent: "#f2b846",
    finale: { name: "Trial of Honor", icon: "shield", blurb: "Earn the master's bow in the dojo of a hundred mats." },
    map: worldMapArt("samurai-dojo"),
    anchors: [
      { x: 48, y: 87 },
      { x: 50, y: 79 },
      { x: 52, y: 72 },
      { x: 53, y: 65 },
      { x: 50, y: 57 },
      { x: 44, y: 45 },
      { x: 52, y: 37 },
      { x: 57, y: 34 },
      { x: 59, y: 31 },
      { x: 59, y: 25 },
      { x: 58, y: 16 },
    ],
    stops: [
      "Training Ring",
      "Banner Walk",
      "Koi Bridge",
      "Maple Steps",
      "Waterfall Stairs",
      "Guardian Statue",
      "Red Gate",
    ],
  },
  turtle: {
    id: "ancient-turtle-grove",
    name: "Ancient Turtle Grove",
    accent: "#7ee06a",
    finale: { name: "Trial of Patience", icon: "shield", blurb: "Tend the oldest garden until the great tree blooms." },
    map: worldMapArt("ancient-turtle-grove"),
    anchors: [
      { x: 50, y: 94 },
      { x: 49, y: 87 },
      { x: 46, y: 79 },
      { x: 47, y: 74 },
      { x: 49, y: 67 },
      { x: 59, y: 61 },
      { x: 58, y: 55 },
      { x: 53, y: 49 },
      { x: 49, y: 44 },
      { x: 55, y: 39 },
      { x: 52, y: 33 },
      { x: 55, y: 23 },
      { x: 55, y: 18 },
    ],
    stops: [
      "Mossy Steps",
      "Turtle Guardians",
      "Glowshroom Pond",
      "Ancient Bridge",
      "Spring Terraces",
      "Elder Ruins",
      "Blooming Stair",
    ],
  },
  owl: {
    id: "arcane-library",
    name: "Arcane Library",
    accent: "#8f7bff",
    finale: { name: "Trial of Wisdom", icon: "book", blurb: "Find the one true spell among a million books." },
    map: worldMapArt("arcane-library"),
    anchors: [
      { x: 47, y: 92 },
      { x: 49, y: 85 },
      { x: 50, y: 78 },
      { x: 54, y: 73 },
      { x: 54, y: 66 },
      { x: 52, y: 60 },
      { x: 51, y: 55 },
      { x: 56, y: 48 },
      { x: 57, y: 42 },
      { x: 60, y: 37 },
      { x: 59, y: 31 },
      { x: 56, y: 23 },
      { x: 55, y: 18 },
    ],
    stops: [
      "Spell Circle",
      "Candle Steps",
      "Floating Tomes",
      "Globe Gallery",
      "Rune Balcony",
      "Star Atrium",
      "Crystal Archive",
    ],
  },
  wolf: {
    id: "moonlit-wolf-den",
    name: "Moonlit Wolf Den",
    accent: "#b06bff",
    finale: { name: "Trial of the Moon", icon: "star", blurb: "Answer the pack's howl under the silver moon." },
    map: worldMapArt("moonlit-wolf-den"),
    anchors: [
      { x: 46, y: 95 },
      { x: 46, y: 88 },
      { x: 49, y: 83 },
      { x: 54, y: 78 },
      { x: 55, y: 72 },
      { x: 49, y: 66 },
      { x: 49, y: 62 },
      { x: 54, y: 57 },
      { x: 61, y: 52 },
      { x: 63, y: 48 },
      { x: 55, y: 42 },
      { x: 55, y: 39 },
      { x: 62, y: 33 },
      { x: 63, y: 30 },
      { x: 59, y: 25 },
      { x: 60, y: 18 },
    ],
    stops: [
      "Lantern Trail",
      "Crystal Blooms",
      "River Crossing",
      "Banner Bridge",
      "Howling Cliffs",
      "Guardian Statues",
      "Moon Steps",
    ],
  },
  phoenix: {
    id: "phoenix-sky-nest",
    name: "Phoenix Sky Nest",
    accent: "#ffd76a",
    finale: { name: "Trial of Dawn", icon: "flame", blurb: "Carry the first light of morning to the highest nest." },
    map: worldMapArt("phoenix-sky-nest"),
    anchors: [
      { x: 59, y: 95 },
      { x: 58, y: 88 },
      { x: 55, y: 82 },
      { x: 55, y: 77 },
      { x: 54, y: 69 },
      { x: 52, y: 65 },
      { x: 52, y: 59 },
      { x: 60, y: 55 },
      { x: 67, y: 50 },
      { x: 59, y: 45 },
      { x: 52, y: 42 },
      { x: 51, y: 38 },
      { x: 57, y: 34 },
      { x: 55, y: 29 },
      { x: 55, y: 23 },
      { x: 58, y: 18 },
    ],
    stops: [
      "Sunrise Plaza",
      "Ember Bridge",
      "Nest Isles",
      "Golden Terrace",
      "Lava Falls",
      "Crystal Roost",
      "Flame Banners",
    ],
  },
  forest: {
    id: "enchanted-forest",
    name: "Enchanted Forest",
    accent: "#7ee06a",
    finale: { name: "Trial of Wonder", icon: "sparkle", blurb: "Wake the sleeping heart of the oldest woods." },
    map: worldMapArt("enchanted-forest"),
    anchors: [
      { x: 50, y: 93 },
      { x: 56, y: 86 },
      { x: 55, y: 80 },
      { x: 53, y: 75 },
      { x: 54, y: 69 },
      { x: 51, y: 66 },
      { x: 55, y: 61 },
      { x: 61, y: 53 },
      { x: 56, y: 49 },
      { x: 53, y: 45 },
      { x: 55, y: 41 },
      { x: 60, y: 36 },
      { x: 56, y: 32 },
      { x: 59, y: 29 },
      { x: 58, y: 25 },
      { x: 57, y: 21 },
    ],
    stops: [
      "Petal Plaza",
      "Fairy Bridges",
      "Glowshroom Grove",
      "Singing Stream",
      "Lantern Stairs",
      "Treehouse Rise",
      "Rainbow Falls",
    ],
  },
  pirate: {
    id: "pirate-treasure-isles",
    name: "Pirate Treasure Isles",
    accent: "#ff9a3d",
    finale: { name: "Treasure Trial", icon: "chest", blurb: "Follow the last map to the island no chart remembers." },
    map: worldMapArt("pirate-treasure-isles"),
    anchors: [
      { x: 46, y: 95 },
      { x: 49, y: 90 },
      { x: 52, y: 84 },
      { x: 53, y: 78 },
      { x: 57, y: 73 },
      { x: 60, y: 67 },
      { x: 62, y: 63 },
      { x: 60, y: 57 },
      { x: 57, y: 52 },
      { x: 56, y: 46 },
      { x: 55, y: 41 },
      { x: 57, y: 36 },
      { x: 60, y: 31 },
      { x: 61, y: 27 },
      { x: 59, y: 22 },
      { x: 60, y: 17 },
    ],
    stops: [
      "Landing Dock",
      "Boardwalk Bay",
      "Shipwreck Cove",
      "Treasure Isle",
      "Palm Lagoon",
      "Watchtower Rock",
      "Golden Stairs",
    ],
  },
};

interface WorldSpec {
  id: string;
  name: string;
  theme: ThemeId;
  map: string;
  accent: string;
  anchors: { x: number; y: number }[];
  stops: string[]; // 7 landmark names, in path order
  finale: { name: string; icon: string; blurb: string };
  reward: { companion: string; blurb: string };
}

const SPECS: WorldSpec[] = [
  {
    id: "shadow-ninja",
    name: "Shadow Ninja Village",
    theme: "ninja",
    map: worldMapArt("shadow-ninja"),
    accent: "#6ea8ff",
    // winding stone path: bottom-left cluster → across the bridge → then
    // switchbacks up the hillside to the great pagoda at the top
    anchors: [
      { x: 34, y: 74 },
      { x: 28, y: 63 },
      { x: 33, y: 57 },
      { x: 44, y: 52 },
      { x: 60, y: 47 },
      { x: 47, y: 40 },
      { x: 64, y: 36 },
      { x: 49, y: 29 },
      { x: 63, y: 26 },
      { x: 54, y: 20 },
      { x: 60, y: 16 },
    ],
    stops: [
      "Bamboo Gate",
      "Lantern Bridge",
      "Whispering Forest",
      "Rooftop Run",
      "Moon Shrine",
      "Smoke Canyon",
      "Blossom Peak",
    ],
    finale: {
      name: "Discipline Trial",
      icon: "sword",
      blurb: "Face the village elders at the Shadow Citadel and prove your focus.",
    },
    reward: { companion: "fox", blurb: "Frost the Crystal Fox awakens" },
  },
  {
    id: "samurai",
    name: "Legend of the Samurai",
    theme: "samurai",
    map: worldMapArt("samurai"),
    accent: "#f4b740",
    // golden road: village gate → wooden bridge → winding climb with a left
    // bulge → small zigzag → the castle entrance
    anchors: [
      { x: 43, y: 79 },
      { x: 47, y: 70 },
      { x: 49, y: 62 },
      { x: 48, y: 54 },
      { x: 45, y: 49 },
      { x: 45, y: 44 },
      { x: 49, y: 38 },
      { x: 52, y: 33 },
      { x: 57, y: 29 },
      { x: 55, y: 26 },
      { x: 63, y: 23 },
    ],
    stops: [
      "Village Gate",
      "Rice Terraces",
      "Golden Maple Road",
      "Mountain Dojo",
      "Sacred Torii",
      "Thunder Pass",
      "Temple of Echoes",
    ],
    finale: {
      name: "Honor Trial",
      icon: "flame",
      blurb: "Climb the Summit of Legends and show the council your courage.",
    },
    reward: { companion: "samurai", blurb: "Kenji the Baby Samurai awakens" },
  },
  {
    id: "speed-realm",
    name: "Speed Realm",
    theme: "speed",
    map: worldMapArt("speed-realm"),
    accent: "#22d3ee",
    // neon racetrack: launch pad → right sweep → left sweep across the sky
    // bridge → final switchback up into the trophy tower
    anchors: [
      { x: 48, y: 85 },
      { x: 48, y: 77 },
      { x: 51, y: 70 },
      { x: 56, y: 63 },
      { x: 62, y: 57 },
      { x: 65, y: 51 },
      { x: 60, y: 45 },
      { x: 52, y: 42 },
      { x: 44, y: 40 },
      { x: 41, y: 35 },
      { x: 46, y: 30 },
      { x: 54, y: 27 },
      { x: 60, y: 29 },
      { x: 56, y: 23 },
      { x: 53, y: 19 },
    ],
    stops: [
      "Launch Pad",
      "Neon Loop",
      "Crystal Cavern",
      "Skyway Sprint",
      "Magnet Rail",
      "Storm Circuit",
      "Prism Tower",
    ],
    finale: {
      name: "Speed Championship",
      icon: "trophy",
      blurb: "Race for the golden cup at the Infinity Ring — the fastest quest of all.",
    },
    reward: { companion: "robot", blurb: "Bolt the Little Robot awakens" },
  },
];

/* Evenly space `count` points along the anchor polyline (by arc length),
   so nodes follow the painted path no matter how anchors are spaced. */
function tracePath(anchors: { x: number; y: number }[], count: number) {
  const segs: number[] = [];
  let total = 0;
  for (let i = 1; i < anchors.length; i++) {
    const d = Math.hypot(anchors[i].x - anchors[i - 1].x, anchors[i].y - anchors[i - 1].y);
    segs.push(d);
    total += d;
  }
  const pts: { x: number; y: number }[] = [];
  for (let n = 0; n < count; n++) {
    const target = (n / (count - 1)) * total;
    let acc = 0;
    let i = 0;
    while (i < segs.length - 1 && acc + segs[i] < target) {
      acc += segs[i];
      i += 1;
    }
    const t = segs[i] === 0 ? 0 : (target - acc) / segs[i];
    pts.push({
      x: +(anchors[i].x + (anchors[i + 1].x - anchors[i].x) * t).toFixed(2),
      y: +(anchors[i].y + (anchors[i + 1].y - anchors[i].y) * t).toFixed(2),
    });
  }
  return pts;
}

/* 36 nodes along a path: quiet steps, 7 named landmarks, the trial at 36.
   worldIdx positions the requires values within the campaign (0-3). */
function buildLevels(
  idPrefix: string,
  anchors: { x: number; y: number }[],
  stops: string[],
  finaleName: string,
  worldIdx: number
): MapNode[] {
  const pts = tracePath(anchors, CHAPTER_SPAN);
  return pts.map((p, i) => {
    const step = i + 1;
    const landmarkIdx = LANDMARK_STEPS.indexOf(step);
    const kind: NodeKind =
      step === CHAPTER_SPAN ? "final" : landmarkIdx >= 0 ? "landmark" : "quest";
    return {
      id: `${idPrefix}-${step}`,
      name:
        kind === "final" ? finaleName : kind === "landmark" ? stops[landmarkIdx] : `Step ${step}`,
      x: p.x,
      y: p.y,
      requires: worldIdx * CHAPTER_SPAN + step,
      kind,
    };
  });
}

function buildWorld(spec: WorldSpec, chapterIdx: number): WorldMapDef {
  return {
    ...spec,
    levels: buildLevels(spec.theme, spec.anchors, spec.stops, spec.finale.name, chapterIdx),
  };
}

export const WORLD_MAPS: Record<ThemeId, WorldMapDef> = Object.fromEntries(
  SPECS.map((s, i) => [s.theme, buildWorld(s, i)])
) as Record<ThemeId, WorldMapDef>;

/* A finale world with delivered map art becomes a full, renderable world:
   36 nodes at campaign steps 109..144, ending at the Legend Ceremony gate. */
export function finaleWorldMap(species: string): WorldMapDef | null {
  const fw = FINALE_WORLDS[species];
  if (!fw?.map || !fw.anchors || !fw.stops) return null;
  return {
    id: fw.id,
    name: fw.name,
    map: fw.map,
    accent: fw.accent,
    anchors: fw.anchors,
    finale: fw.finale,
    reward: { companion: species, blurb: `${fw.name} complete — Legendary!` },
    levels: buildLevels(
      `${species}-finale`,
      fw.anchors,
      fw.stops,
      fw.finale.name,
      SHARED_WORLDS.length
    ),
  };
}

export type NodeState = "completed" | "current" | "locked";

/** State of every node given how many quests the child has completed. */
export function nodeStates(levels: MapNode[], tasksCompleted: number): NodeState[] {
  let currentAssigned = false;
  return levels.map((lvl) => {
    if (tasksCompleted >= lvl.requires) return "completed";
    if (!currentAssigned) {
      currentAssigned = true;
      return "current";
    }
    return "locked";
  });
}

/** Progress summary for captions: cleared count + the node you're on. */
export function worldProgress(world: WorldMapDef, tasksCompleted: number) {
  const states = nodeStates(world.levels, tasksCompleted);
  const completed = states.filter((s) => s === "completed").length;
  const currentIdx = states.indexOf("current");
  return {
    completed,
    total: world.levels.length,
    current: currentIdx >= 0 ? world.levels[currentIdx] : null,
    states,
  };
}

/* ---------- Campaign progression ----------
   All functions below take the CAMPAIGN STEP: the active bond's steps_done —
   difficulty-weighted (easy/medium 1, hard 2, epic 3) so real effort moves
   the map faster. Every new companion campaign starts at step 0 and runs to
   CAMPAIGN_TOTAL. Node `requires` values (1..108) are campaign steps, so the
   maps read the step directly. The finale world occupies steps 109..144. */

/** The active campaign's progress — weighted steps earned during this bond
    (older cached rows without steps_done fall back to the quest count). */
export function campaignStep(
  bond: Pick<CompanionBond, "quests_done" | "steps_done"> | null
): number {
  return Math.min(bond?.steps_done ?? bond?.quests_done ?? 0, CAMPAIGN_TOTAL);
}

/** Which of the 4 campaign worlds the hero is in right now (0-3). */
export function campaignWorldIndex(step: number): number {
  return Math.min(Math.floor(step / CHAPTER_SPAN), WORLDS_PER_CAMPAIGN - 1);
}

/** True once the campaign has reached its companion-exclusive finale world. */
export function inFinaleWorld(step: number): boolean {
  return step >= CHAPTER_SPAN * SHARED_WORLDS.length && step < CAMPAIGN_TOTAL;
}

/** Campaign completed = the finale world's last trial is cleared. */
export function campaignCompleted(step: number): boolean {
  return step >= CAMPAIGN_TOTAL;
}

/** A shared world is complete once its final trial is cleared this campaign. */
export function worldCompleted(theme: ThemeId, step: number): boolean {
  const levels = WORLD_MAPS[theme].levels;
  return step >= levels[levels.length - 1].requires;
}

/** How many SHARED worlds this campaign has fully cleared (0-3). */
export function worldsCompleted(step: number): number {
  let n = 0;
  for (const t of SHARED_WORLDS) {
    if (worldCompleted(t, step)) n += 1;
    else break;
  }
  return n;
}

/** A shared world opens once every world before it is complete (this campaign). */
export function worldUnlocked(theme: ThemeId, step: number): boolean {
  const idx = SHARED_WORLDS.indexOf(theme);
  return idx <= worldsCompleted(step);
}

/** The shared world whose MAP should be shown right now (the finale world has
    no painted map yet, so its segment keeps showing the last shared map). */
export function currentChapter(step: number): ThemeId {
  return SHARED_WORLDS[Math.min(worldsCompleted(step), SHARED_WORLDS.length - 1)];
}

/** The next shared world after this one, if any. */
export function nextChapter(theme: ThemeId): ThemeId | null {
  const idx = SHARED_WORLDS.indexOf(theme);
  return idx >= 0 && idx < SHARED_WORLDS.length - 1 ? SHARED_WORLDS[idx + 1] : null;
}

/** The world map the active campaign should RENDER right now:
    the child's chosen shared world during worlds 1-3, then the companion's
    exclusive finale world once its segment begins (falling back to the last
    shared map for companions whose finale art hasn't been delivered yet). */
export function campaignWorld(species: string, theme: ThemeId, step: number): WorldMapDef {
  if (step >= CHAPTER_SPAN * SHARED_WORLDS.length) {
    return finaleWorldMap(species) ?? WORLD_MAPS[currentChapter(step)];
  }
  return WORLD_MAPS[theme];
}

/* ---------- Lifetime progression (species unlocks only) ----------
   Companion unlock rules stay keyed to the hero's LIFETIME totals — once a
   world has been cleared in any campaign it stays cleared for unlock
   purposes. Mirrors the thresholds in the bond_companion SQL function. */

export function lifetimeWorldsCleared(lifetimeSteps: number): number {
  let n = 0;
  for (let i = 0; i < SHARED_WORLDS.length; i++) {
    if (lifetimeSteps >= (i + 1) * CHAPTER_SPAN) n += 1;
    else break;
  }
  return n;
}

/** Lifetime weighted steps across every bond — the input for
    lifetimeWorldsCleared (mirrors the sum in bond_companion SQL). */
export function lifetimeSteps(bonds: Pick<CompanionBond, "quests_done" | "steps_done">[]): number {
  return bonds.reduce((sum, b) => sum + (b.steps_done ?? b.quests_done ?? 0), 0);
}
