/* World-map configuration — worlds are CHAPTERS of one adventure.

   Each chapter spans 36 quests and paints 36 nodes onto its map: every
   completed quest moves the hero one step along the path. Node positions are
   generated by interpolating along hand-placed percentage ANCHORS that trace
   the painted path (x = % from left, y = % from top) — tweak the anchors to
   re-shape a world's route, no other changes needed.

   Along the way, seven named LANDMARKS mark memorable places, and node 36 is
   the FINAL CHAPTER CHALLENGE — a boss-style trial. Clearing it completes the
   chapter: a companion awakens, and the next world unlocks. */

import { ThemeId } from "./game";

export type NodeKind = "quest" | "landmark" | "final";

export interface MapNode {
  id: string;
  name: string;
  x: number; // % from left of the map image
  y: number; // % from top of the map image
  requires: number; // total quests completed needed to clear this node
  kind: NodeKind;
}

export interface WorldMapDef {
  id: string; // matches the public/worlds/<id>/ folder
  name: string;
  theme: ThemeId;
  map: string; // path under /public
  accent: string; // themed glow colour for the path + nodes
  /** Hand-placed waypoints tracing the painted path — adjust these freely. */
  anchors: { x: number; y: number }[];
  /** The boss-style milestone that closes the chapter (node 36). */
  finale: { name: string; icon: string; blurb: string };
  /** What completing the chapter unlocks. */
  reward: { companion: string; blurb: string };
  levels: MapNode[];
}

/* Every chapter is 36 quests; landmarks sit at these steps within it. */
export const CHAPTER_SPAN = 36;
const LANDMARK_STEPS = [1, 4, 8, 13, 18, 24, 30];

/* The adventure's chapter order — complete one world to unlock the next. */
export const WORLD_ORDER: ThemeId[] = ["ninja", "samurai", "speed"];

interface WorldSpec {
  id: string;
  name: string;
  theme: ThemeId;
  map: string;
  accent: string;
  anchors: { x: number; y: number }[];
  stops: string[]; // 7 landmark names, in path order
  finale: { name: string; icon: string; blurb: string };
  reward: { companion: string; blurb: string };
}

const SPECS: WorldSpec[] = [
  {
    id: "shadow-ninja-village",
    name: "Shadow Ninja Village",
    theme: "ninja",
    map: "/worlds/shadow-ninja-village/map.png",
    accent: "#6ea8ff",
    // winding stone path: bottom-left cluster → bridge → castle top-right
    anchors: [
      { x: 34, y: 74 },
      { x: 27, y: 63 },
      { x: 39, y: 56 },
      { x: 50, y: 53 },
      { x: 58, y: 47 },
      { x: 65, y: 42 },
      { x: 70, y: 33 },
      { x: 72, y: 24 },
    ],
    stops: [
      "Bamboo Gate",
      "Lantern Bridge",
      "Whispering Forest",
      "Rooftop Run",
      "Moon Shrine",
      "Smoke Canyon",
      "Blossom Peak",
    ],
    finale: {
      name: "Discipline Trial",
      icon: "sword",
      blurb: "Face the village elders at the Shadow Citadel and prove your focus.",
    },
    reward: { companion: "ninja", blurb: "Kage the Tiny Ninja awakens" },
  },
  {
    id: "legend-samurai",
    name: "Legend of the Samurai",
    theme: "samurai",
    map: "/worlds/legend-samurai/map.png",
    accent: "#f4b740",
    // golden path: bottom-centre → red bridges → castle top-right
    anchors: [
      { x: 49, y: 82 },
      { x: 49, y: 70 },
      { x: 53, y: 60 },
      { x: 56, y: 50 },
      { x: 57, y: 42 },
      { x: 56, y: 34 },
      { x: 61, y: 27 },
      { x: 66, y: 19 },
    ],
    stops: [
      "Village Gate",
      "Rice Terraces",
      "Golden Maple Road",
      "Mountain Dojo",
      "Sacred Torii",
      "Thunder Pass",
      "Temple of Echoes",
    ],
    finale: {
      name: "Honor Trial",
      icon: "flame",
      blurb: "Climb the Summit of Legends and show the council your courage.",
    },
    reward: { companion: "samurai", blurb: "Kenji the Baby Samurai awakens" },
  },
  {
    id: "speed-realm",
    name: "Speed Realm",
    theme: "speed",
    map: "/worlds/speed-realm/map.png",
    accent: "#22d3ee",
    // neon racetrack: bottom-centre → loop → trophy tower top-centre
    anchors: [
      { x: 50, y: 88 },
      { x: 55, y: 77 },
      { x: 64, y: 67 },
      { x: 68, y: 56 },
      { x: 58, y: 48 },
      { x: 49, y: 42 },
      { x: 49, y: 32 },
      { x: 53, y: 20 },
    ],
    stops: [
      "Launch Pad",
      "Neon Loop",
      "Crystal Cavern",
      "Skyway Sprint",
      "Magnet Rail",
      "Storm Circuit",
      "Prism Tower",
    ],
    finale: {
      name: "Speed Championship",
      icon: "trophy",
      blurb: "Race for the golden cup at the Infinity Ring — the fastest quest of all.",
    },
    reward: { companion: "robot", blurb: "Bolt the Little Robot awakens" },
  },
];

/* Evenly space `count` points along the anchor polyline (by arc length),
   so nodes follow the painted path no matter how anchors are spaced. */
function tracePath(anchors: { x: number; y: number }[], count: number) {
  const segs: number[] = [];
  let total = 0;
  for (let i = 1; i < anchors.length; i++) {
    const d = Math.hypot(anchors[i].x - anchors[i - 1].x, anchors[i].y - anchors[i - 1].y);
    segs.push(d);
    total += d;
  }
  const pts: { x: number; y: number }[] = [];
  for (let n = 0; n < count; n++) {
    const target = (n / (count - 1)) * total;
    let acc = 0;
    let i = 0;
    while (i < segs.length - 1 && acc + segs[i] < target) {
      acc += segs[i];
      i += 1;
    }
    const t = segs[i] === 0 ? 0 : (target - acc) / segs[i];
    pts.push({
      x: +(anchors[i].x + (anchors[i + 1].x - anchors[i].x) * t).toFixed(2),
      y: +(anchors[i].y + (anchors[i + 1].y - anchors[i].y) * t).toFixed(2),
    });
  }
  return pts;
}

function buildWorld(spec: WorldSpec, chapterIdx: number): WorldMapDef {
  const pts = tracePath(spec.anchors, CHAPTER_SPAN);
  const levels: MapNode[] = pts.map((p, i) => {
    const step = i + 1;
    const landmarkIdx = LANDMARK_STEPS.indexOf(step);
    const kind: NodeKind =
      step === CHAPTER_SPAN ? "final" : landmarkIdx >= 0 ? "landmark" : "quest";
    return {
      id: `${spec.theme}-${step}`,
      name:
        kind === "final"
          ? spec.finale.name
          : kind === "landmark"
            ? spec.stops[landmarkIdx]
            : `Step ${step}`,
      x: p.x,
      y: p.y,
      requires: chapterIdx * CHAPTER_SPAN + step,
      kind,
    };
  });
  return { ...spec, levels };
}

export const WORLD_MAPS: Record<ThemeId, WorldMapDef> = Object.fromEntries(
  SPECS.map((s, i) => [s.theme, buildWorld(s, i)])
) as Record<ThemeId, WorldMapDef>;

export type NodeState = "completed" | "current" | "locked";

/** State of every node given how many quests the child has completed. */
export function nodeStates(levels: MapNode[], tasksCompleted: number): NodeState[] {
  let currentAssigned = false;
  return levels.map((lvl) => {
    if (tasksCompleted >= lvl.requires) return "completed";
    if (!currentAssigned) {
      currentAssigned = true;
      return "current";
    }
    return "locked";
  });
}

/** Progress summary for captions: cleared count + the node you're on. */
export function worldProgress(world: WorldMapDef, tasksCompleted: number) {
  const states = nodeStates(world.levels, tasksCompleted);
  const completed = states.filter((s) => s === "completed").length;
  const currentIdx = states.indexOf("current");
  return {
    completed,
    total: world.levels.length,
    current: currentIdx >= 0 ? world.levels[currentIdx] : null,
    states,
  };
}

/* ---------- Chapters ----------
   Worlds are chapters of one adventure, not skins. A chapter is complete when
   its final challenge is cleared; only then does the next chapter open. */

export function worldCompleted(theme: ThemeId, tasksCompleted: number): boolean {
  const levels = WORLD_MAPS[theme].levels;
  return tasksCompleted >= levels[levels.length - 1].requires;
}

/** How many chapters the hero has fully cleared (0-3). */
export function worldsCompleted(tasksCompleted: number): number {
  let n = 0;
  for (const t of WORLD_ORDER) {
    if (worldCompleted(t, tasksCompleted)) n += 1;
    else break;
  }
  return n;
}

/** A chapter opens once every chapter before it is complete. */
export function worldUnlocked(theme: ThemeId, tasksCompleted: number): boolean {
  const idx = WORLD_ORDER.indexOf(theme);
  return idx <= worldsCompleted(tasksCompleted);
}

/** The chapter the hero should be adventuring in right now. */
export function currentChapter(tasksCompleted: number): ThemeId {
  return WORLD_ORDER[Math.min(worldsCompleted(tasksCompleted), WORLD_ORDER.length - 1)];
}

/** The next chapter after this one, if any. */
export function nextChapter(theme: ThemeId): ThemeId | null {
  const idx = WORLD_ORDER.indexOf(theme);
  return idx >= 0 && idx < WORLD_ORDER.length - 1 ? WORLD_ORDER[idx + 1] : null;
}
